// ================================================================================
// File automatically generated by katie.exe v1.4
// http://www.console-dev.de
// 
// WARNING: All changes made in this file will be lost!
// ================================================================================

#ifndef RESOURCEDATA_H
#define RESOURCEDATA_H

#ifdef __cplusplus
	extern "C"{
#endif

// gfx/bg15.pal
#define RES_BG15_PAL	0
#define RES_BG15_PAL_SIZE	32
#define RES_BG15_PAL_SIZEPADDED	32
#define RES_BG15_PAL_SIZE16	16
#define RES_BG15_PAL_SIZE16PADDED	16
#define RES_BG15_PAL_SIZE32	8
#define RES_BG15_PAL_SIZE32PADDED	8

// gfx/charset8x8.map
#define RES_CHARSET8X8_MAP	32
#define RES_CHARSET8X8_MAP_SIZE	240
#define RES_CHARSET8X8_MAP_SIZEPADDED	240
#define RES_CHARSET8X8_MAP_SIZE16	120
#define RES_CHARSET8X8_MAP_SIZE16PADDED	120
#define RES_CHARSET8X8_MAP_SIZE32	60
#define RES_CHARSET8X8_MAP_SIZE32PADDED	60

// gfx/charset8x8.raw
#define RES_CHARSET8X8_RAW	272
#define RES_CHARSET8X8_RAW_SIZE	3200
#define RES_CHARSET8X8_RAW_SIZEPADDED	3200
#define RES_CHARSET8X8_RAW_SIZE16	1600
#define RES_CHARSET8X8_RAW_SIZE16PADDED	1600
#define RES_CHARSET8X8_RAW_SIZE32	800
#define RES_CHARSET8X8_RAW_SIZE32PADDED	800


#define ResData(_identifier)	((const void*)&__ResourceData__[_identifier])
#define ResData8(_identifier)	((const unsigned char*)&__ResourceData__[_identifier])
#define ResData8X(_identifier, _index)	((const unsigned char*)&__ResourceData__[(_identifier)+(_index)])
#define ResData16(_identifier)	((const unsigned short*)&__ResourceData__[_identifier])
#define ResData16X(_identifier, _index)	((const unsigned short*)&__ResourceData__[(_identifier)+((_index)<<1)])
#define ResData32(_identifier)	((const unsigned long*)&__ResourceData__[_identifier])
#define ResData32X(_identifier, _index)	((const unsigned long*)&__ResourceData__[(_identifier)+((_index)<<2)])
#define ResDataType(_type, _identifier)	((const _type*)&__ResourceData__[_identifier])
#define ResDataTypeX(_type, _identifier, _index)	((const _type*)&__ResourceData__[(_identifier)+((_index)*sizeof(_type)])


extern const unsigned char __ResourceData__[];

#ifdef __cplusplus
	}
#endif

#endif // RESOURCEDATA_H

