.TH "CHANNEL" 3 "Thu May 5 2011" "Version version 0-02" "FAT FuriousAdvanceTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHANNEL \- 
.PP
Un channel représente une colonne de séquences: la GBA dispose de 6 channels.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "u8 \fBsequences\fP [NB_SEQUENCES_IN_ONE_CHANNEL]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Un channel représente une colonne de séquences: la GBA dispose de 6 channels. 
.SH "Documentation des champs"
.PP 
.SS "u8 \fBsequences\fP[NB_SEQUENCES_IN_ONE_CHANNEL]"Un channel possède sa collection de numéro de séquence. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour FAT FuriousAdvanceTracker à partir du code source.
