.TH "COMPOSER" 3 "Thu May 5 2011" "Version version 0-02" "FAT FuriousAdvanceTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COMPOSER \- 
.PP
Définit les données pour le compositeur (écran de composition).  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBnote\fP \fBnotes\fP [8]"
.br
.ti -1c
.RI "u8 \fBtranspose\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définit les données pour le compositeur (écran de composition). 
.SH "Documentation des champs"
.PP 
.SS "\fBnote\fP \fBnotes\fP[8]"Un compositeur contient un certain nombre de notes. 
.SS "u8 \fBtranspose\fP"Définit la valeur de transposition pour le compositeur entier \fBNON IMPLEMENTE\fP. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour FAT FuriousAdvanceTracker à partir du code source.
