.TH "gfx.h" 3 "Thu May 5 2011" "Version version 0-02" "FAT FuriousAdvanceTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gfx.h \- 
.PP
Ce fichier contient toutes les inclusions des fichiers générés par 'gfx2gba'.  

.SH SYNOPSIS
.br
.PP
\fC#include 'gfx/sprite.pal.c'\fP
.br
\fC#include 'gfx/screen.pal.c'\fP
.br
\fC#include 'gfx/intro.pal.c'\fP
.br
\fC#include 'gfx/popup.raw.c'\fP
.br
\fC#include 'gfx/popup.map.c'\fP
.br
\fC#include 'gfx/screen_intro.raw.c'\fP
.br
\fC#include 'gfx/screen_intro.map.c'\fP
.br
\fC#include 'gfx/screen_projet.raw.c'\fP
.br
\fC#include 'gfx/screen_projet.map.c'\fP
.br
\fC#include 'gfx/screen_live.raw.c'\fP
.br
\fC#include 'gfx/screen_live.map.c'\fP
.br
\fC#include 'gfx/screen_composer.raw.c'\fP
.br
\fC#include 'gfx/screen_composer.map.c'\fP
.br
\fC#include 'gfx/screen_song.raw.c'\fP
.br
\fC#include 'gfx/screen_song.map.c'\fP
.br
\fC#include 'gfx/screen_notes.raw.c'\fP
.br
\fC#include 'gfx/screen_notes.map.c'\fP
.br
\fC#include 'gfx/screen_blocks.raw.c'\fP
.br
\fC#include 'gfx/screen_blocks.map.c'\fP
.br
\fC#include 'gfx/screen_instrument_pulse.raw.c'\fP
.br
\fC#include 'gfx/screen_instrument_pulse.map.c'\fP
.br
\fC#include 'gfx/screen_instrument_wave.raw.c'\fP
.br
\fC#include 'gfx/screen_instrument_wave.map.c'\fP
.br
\fC#include 'gfx/screen_instrument_noise.raw.c'\fP
.br
\fC#include 'gfx/screen_instrument_noise.map.c'\fP
.br
\fC#include 'gfx/screen_instrument_sample.raw.c'\fP
.br
\fC#include 'gfx/screen_instrument_sample.map.c'\fP
.br
\fC#include 'gfx/screen_effects.raw.c'\fP
.br
\fC#include 'gfx/screen_effects.map.c'\fP
.br
\fC#include 'gfx/actual_screen_popup.raw.c'\fP
.br
\fC#include 'gfx/cursor_popup.raw.c'\fP
.br
\fC#include 'gfx/cursor_instrument_tabulation.raw.c'\fP
.br
\fC#include 'gfx/cursor_change.raw.c'\fP
.br
\fC#include 'gfx/cursor1.raw.c'\fP
.br
\fC#include 'gfx/cursor2.raw.c'\fP
.br
\fC#include 'gfx/cursor3.raw.c'\fP
.br
\fC#include 'gfx/cursor2_player.raw.c'\fP
.br
\fC#include 'gfx/cursor3_player.raw.c'\fP
.br
\fC#include 'gfx/envdir_0.raw.c'\fP
.br
\fC#include 'gfx/envdir_1.raw.c'\fP
.br
\fC#include 'gfx/waveduty_0.raw.c'\fP
.br
\fC#include 'gfx/waveduty_1.raw.c'\fP
.br
\fC#include 'gfx/waveduty_2.raw.c'\fP
.br
\fC#include 'gfx/waveduty_3.raw.c'\fP
.br

.SH "Description détaillée"
.PP 
Ce fichier contient toutes les inclusions des fichiers générés par 'gfx2gba'. 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour FAT FuriousAdvanceTracker à partir du code source.
