.TH "INSTRUMENT" 3 "Thu May 5 2011" "Version version 0-02" "FAT FuriousAdvanceTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INSTRUMENT \- 
.PP
L'instrument possède divers paramètres utiles pour modifier la sonorité d'une note: chaque note est attachée à un instrument.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "u8 \fBtype\fP"
.br
.ti -1c
.RI "u8 \fBsweep\fP"
.br
.ti -1c
.RI "u8 \fBenvelope\fP"
.br
.ti -1c
.RI "u8 \fBwavedutyOrPolynomialStep\fP"
.br
.ti -1c
.RI "u8 \fBsoundlength\fP"
.br
.ti -1c
.RI "u8 \fBloopmode\fP"
.br
.ti -1c
.RI "u8 \fBvoiceAndBank\fP"
.br
.ti -1c
.RI "u8 \fBvolumeRatio\fP"
.br
.ti -1c
.RI "u8 \fBtable\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
L'instrument possède divers paramètres utiles pour modifier la sonorité d'une note: chaque note est attachée à un instrument. 
.SH "Documentation des champs"
.PP 
.SS "u8 \fBenvelope\fP"Valeur d'enveloppe. L'enveloppe contient trois paramètres: 'steptime', 'envdir', 'volume'. 
.SS "u8 \fBloopmode\fP"Mode de durée du son : 1=timed, 0=continuous . 
.SS "u8 \fBsoundlength\fP"Stocke la durée du son: attention, ce paramètre ne sera appliqué que si loopmode = 1. 
.SS "u8 \fBsweep\fP"Valeur de 'sweep'. Le 'sweep' n'est applicable que sur le channel 1. 
.SS "u8 \fBtable\fP"Numéro de table de commandes à appliquer pour chaque note assignée à cet instrument. 
.SS "u8 \fBtype\fP"Le type de l'instrument: PULSE1, PULSE2, WAVE, NOISE, SAMPLEA, SAMPLEB 
.SS "u8 \fBvoiceAndBank\fP"Ce paramètre agrége plusieurs autres paramètres dédiés aux instruments de type WAVE : 'voice', 'bank', 'bankmode'. 
.SS "u8 \fBvolumeRatio\fP"Stocke le volume pour un instrument de type WAVE. 
.SS "u8 \fBwavedutyOrPolynomialStep\fP"Contient la valeur du paramètre 'wave' pour les instruments de type PULSE \fBOU\fP la valeur du paramètre 'polystep' pour les instruments de type NOISE 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour FAT FuriousAdvanceTracker à partir du code source.
