.TH "main.c" 3 "Thu May 5 2011" "Version version 0-02" "FAT FuriousAdvanceTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.PP
Fichier code source principal avec la fonction main et l'inclusion de \fBfat.h\fP.  

.SH SYNOPSIS
.br
.PP
\fC#include <mygba.h>\fP
.br
\fC#include 'soundApi/soundApi.h'\fP
.br
\fC#include 'fat.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFAT_VERSION\fP   '0-02'"
.br
.RI "\fISi cette variable est positionné à 1, le mode DEBUG pour \fBFAT\fP est activé. Certaines, informations seront affichées. \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "\fIFonction main. Si vous lisez le code source, il est judicieux de commencer par comprendre cette fonction. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Fichier code source principal avec la fonction main et l'inclusion de \fBfat.h\fP. 


.SH "Documentation des macros"
.PP 
.SS "#define FAT_VERSION   '0-02'"
.PP
Si cette variable est positionné à 1, le mode DEBUG pour \fBFAT\fP est activé. Certaines, informations seront affichées. Version actuelle de \fBFAT\fP. 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour FAT FuriousAdvanceTracker à partir du code source.
