.TH "screen_live.h" 3 "Thu May 5 2011" "Version version 0-02" "FAT FuriousAdvanceTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
screen_live.h \- 
.PP
Fichier contenant toutes les fonctions pour gérer l'écran LIVE.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBFAT_screenLive_init\fP ()"
.br
.RI "\fIInitialisation de l'écran. \fP"
.ti -1c
.RI "void \fBFAT_screenLive_checkButtons\fP ()"
.br
.RI "\fITeste les actions utilisateurs. \fP"
.ti -1c
.RI "void \fBFAT_screenLive_mainFunc\fP ()"
.br
.RI "\fIFonction principale de l'écran (callback). \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBFAT_screenLive_isPopuped\fP = 0"
.br
.RI "\fIPermet de savoir si la popup de déplacement est affichée au dessus de l'écran. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Fichier contenant toutes les fonctions pour gérer l'écran LIVE. 


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour FAT FuriousAdvanceTracker à partir du code source.
