.TH "screen_effects.h" 3 "Thu May 5 2011" "Version version 0-02" "FAT FuriousAdvanceTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
screen_effects.h \- 
.PP
Ce fichier contient toutes les fonctions utiles pour la gestion de l'écran EFFECTS.  

.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBFAT_screenEffects_init\fP ()"
.br
.RI "\fIInitialisation de l'écran. \fP"
.ti -1c
.RI "void \fBFAT_screenEffects_checkButtons\fP ()"
.br
.RI "\fICette fonction permet de tester les actions utilisateurs sur l'écran. \fP"
.ti -1c
.RI "void \fBFAT_screenEffects_mainFunc\fP ()"
.br
.RI "\fIFonction principale de l'écran (callback). \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBFAT_screenEffects_isPopuped\fP = 0"
.br
.RI "\fIPermet de savoir si la popup est affichée au dessus de l'écran ou non. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Ce fichier contient toutes les fonctions utiles pour la gestion de l'écran EFFECTS. 

Cet écran est globalement similaire à celui des tables dans LSDJ. 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour FAT FuriousAdvanceTracker à partir du code source.
