.TH "SEQUENCE" 3 "Thu May 5 2011" "Version version 0-02" "FAT FuriousAdvanceTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SEQUENCE \- 
.PP
Une séquence contient un certain nombre de blocks.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "u8 \fBblocks\fP [NB_BLOCKS_IN_SEQUENCE]"
.br
.ti -1c
.RI "u8 \fBtranspose\fP [NB_BLOCKS_IN_SEQUENCE]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Une séquence contient un certain nombre de blocks. 
.SH "Documentation des champs"
.PP 
.SS "u8 \fBblocks\fP[NB_BLOCKS_IN_SEQUENCE]"Un tableau contenant des numéros de blocks. 
.SS "u8 \fBtranspose\fP[NB_BLOCKS_IN_SEQUENCE]"Chaque block peut être transposé: on stocke la valeur de transpose ici. On ne peut pas la stocker dans \fBBLOCK\fP, car cela ne permettrait qu'une seule transposition par block. Ici, un block peut être transposé avec telle valeur dans une séquence et telle autre valeur dans une autre séquence. De même, au sein de la même séquence, on peut ainsi transposer différemment chacun des blocks présent. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour FAT FuriousAdvanceTracker à partir du code source.
