.TH "TABLE" 3 "Thu May 5 2011" "Version version 0-02" "FAT FuriousAdvanceTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TABLE \- 
.PP
Définit une table d'effets: soit une liste de commandes.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBeffect\fP \fBeffects\fP [NB_EFFECTS_IN_ONE_TABLE]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définit une table d'effets: soit une liste de commandes. 

Une table possède un nombre défini de commandes. 
.SH "Documentation des champs"
.PP 
.SS "\fBeffect\fP \fBeffects\fP[NB_EFFECTS_IN_ONE_TABLE]"Le tableau des commandes enregistrées dans cette table. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour FAT FuriousAdvanceTracker à partir du code source.
