sam2p screen_blocks.png EPS: screen_blocks.eps
sam2p screen_blocks_complete.png EPS: screen_blocks_complete.eps
sam2p screen_composer.png EPS: screen_composer.eps
sam2p screen_instrument_noise.png EPS: screen_instrument_noise.eps
sam2p screen_instrument_pulse.png EPS: screen_instrument_pulse.eps 
sam2p screen_instrument_wave.png EPS: screen_instrument_wave.eps 
sam2p screen_instrument_sample.png EPS: screen_instrument_sample.eps 
sam2p screen_notes.png EPS: screen_notes.eps 
sam2p screen_notes_complete.png EPS: screen_notes_complete.eps 
sam2p screen_popup.png EPS: screen_popup.eps 
sam2p screen_project.png EPS: screen_project.eps 
sam2p screen_song.png EPS: screen_song.eps 
sam2p screen_song_complete.png EPS: screen_song_complete.eps 
sam2p screen_filesystem_load.png EPS: screen_filesystem_load.eps
sam2p screen_filesystem_save.png EPS: screen_filesystem_save.eps
sam2p confirmation_save.png EPS: confirmation_save.eps
sam2p confirmation_load.png EPS: confirmation_load.eps
